- set:
    bridge:
      domain:
        br_default:
          vlan:
            '10':
              vni:
                '10':
                  flooding:
                    head-end-replication:
                    - 10.10.10.1
                    - 10.10.10.2
            '20':
              vni:
                '20':
                  flooding:
                    head-end-replication:
                    - 10.10.10.4
    interface:
      eth0:
        ip:
          address:
            dhcp: {}
          vrf: mgmt
        type: eth
      lo:
        ip:
          address:
            10.10.10.3/32: {}
        type: loopback
      swp1:
        type: swp
        bridge:
          domain:
            br_default:
              access: 10
      swp2:
        type: swp
        bridge:
          domain:
            br_default:
              access: 20
      swp51:
        type: swp
      swp52:
        type: swp
    nve:
      vxlan:
        mac-learning: on
        enable: on
        source:
          address: 10.10.10.3
    router:
      bgp:
        autonomous-system: 65103
        enable: on
        router-id: 10.10.10.3
    service:
      ntp:
        mgmt:
          server:
            0.cumulusnetworks.pool.ntp.org: {}
            1.cumulusnetworks.pool.ntp.org: {}
            2.cumulusnetworks.pool.ntp.org: {}
            3.cumulusnetworks.pool.ntp.org: {}
    system:
      timezone: Asia/Taipei
      message:
        pre-login: |
          #####################################################################################
          #  Welcome to NVIDIA Cumulus VX (TM)
          #####################################################################################

        post-login: |
          #####################################################################################
          #  You are successfully logged in to: leaf-3
          #####################################################################################
      hostname: leaf03
    vrf:
      default:
        router:
          bgp:
            address-family:
              ipv4-unicast:
                enable: on
                redistribute:
                  connected:
                    enable: on
              l2vpn-evpn:
                enable: on
            enable: on
            neighbor:
              swp51:
                peer-group: underlay
                type: unnumbered
              swp52:
                peer-group: underlay
                type: unnumbered
            peer-group:
              underlay:
                address-family:
                  l2vpn-evpn:
                    enable: on
                remote-as: external  
